name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: |
          pip install requests
          pip install rsa

      - name: 'run 喜马拉雅极速版'

        run: python3 xmly_speed.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须 cookie 多账号 \n 分割
            AUTO_TAKE_OUT: ${{ secrets.AUTO_TAKE_OUT }}  #非必须 是否自动提现支付宝20
            XMLY_ANDROID_AGENT: ${{ secrets.XMLY_ANDROID_AGENT }} #非必须 自定义useragent
            XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非必须 自定义是否刷时长，默认1(即刷时长),反之设置为0
            NOTIFY_TIME: ${{ secrets.NOTIFY_TIME }} #非必须 自定义通知时间
            BARK: ${{ secrets.BARK }}  #非必须 bark通知
            SCKEY: ${{ secrets.SCKEY }}  #非必须 server酱通知
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
            TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
            DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}  #非必须 钉钉机器人token
            DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}  #非必须 钉钉机器人secret
            PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}  #非必须 PushPlus token
            PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}  #非必须 PushPlus 群组编码